### ISSUE TITLE
Unable to deploy the studio

### ISSUE THREAD

**Issue by FrancoisLeclerc** [sanity-io/nextjs-blog-cms-sanity-v3#195]
Hello! first thank you for this great starter kit! I used the previous version of this template about two weeks ago when it was using the app directory of Next.js and everything was fine. I have tried multiple time to install the template following the instructions but every time I do `sanity deploy` I get this error:

```
Error: [vite]: Rollup failed to resolve import "lib/sanity.api" from "/my-website/sanity.config.ts".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
```
Even though I added my environment variable to `.env.local`

Any idea why this is happening?

Thanks!

**Comment by stipsan** [comment]
Hi!

This is because `sanity deploy` can't deploy a NextJS app. It only supports deploying a Sanity Studio 🙂 
You'll need to deploy using [Vercel](https://vercel.com/new), [Netlify](https://app.netlify.com/start) or [another provider that supports NextJS](https://nextjs.org/docs/deployment#self-hosting) 😉

**Comment by FrancoisLeclerc** [comment]
Oh right,,, this makes sense! Thanks a lot!
